<script>
  import { theme } from '$lib/stores/theme';
  import Banner from '$lib/Blocks/Banner.svelte';
  import MetaTags from '$lib/Components/MetaTags.svelte';

  $theme = {
    footer: 'light',
    header: 'light',
  };
  const title = 'Privacy Policy | Climate Policy Radar';
  const excerpt = 'Climate Policy Radar privacy policy';
  const image = 'https://climatepolicyradar.org/images/logo.png';
  const path = '/privacy-policy';
</script>

<MetaTags {title} {excerpt} {image} {path} />

<Banner theme="light" size="sm">
  <h1 slot="heading" class="u-gradient-text--dark-to-blue">Privacy Policy</h1>
  <div class="b-content__wrapper">
    <p>
      Climate Policy Radar CIC, registered at Sustainable County Hall, 3rd
      Floor, Westminster Bridge Road, London SE1 7PB, is a Community Interest
      Company Limited by Guarantee registered in England and Wales (13377442),
      hereafter collectively referred to as 'Climate Policy Radar', ‘CPR’, ‘we’
      or the ‘Company’.
    </p>
    <p>
      We are committed to protecting and respecting your privacy. This Privacy
      Notice will explain how we collect and use your Personal Data and sets out
      your rights under the relevant laws of Data Protection. All details are
      coming soon, but don't worry, you're safe, GDPR and all.
    </p>
  </div>
  <h2>Cookie Policy</h2>
  <div class="b-content__wrapper">
    <h3>What are cookies?</h3>
    <p>
      Cookies are small files that are downloaded onto your computer when you visit a website. They are used by many websites to make them work, or to help them work more efficiently. They also provide us with information about how you use the website.
    </p>
    <p>
      Website operators are required by law - specifically the Privacy and Electronic Communications (EC Directive) (Amendment) Regulations 2011 (UK Regulations) - to provide clear and comprehensive information about the use of cookies, and ensure that users have consented to this use.
    </p>
    <h3>Google Analytics</h3>
    <p>Google Analytics is used to monitor usage of the CPR Website. This information allows us to assess how the Website is used. Anonymous data about usage (eg number of visitors, visitors' country, number of times each page is visited) is collected and aggregated to produce website performance reports.</p>
    <h3>Sharing information via social media platforms</h3>
    <p>Our website and apps may have links embedded into pages on various social media platforms. Cookies generated by those sites are outside of the our control and may change without notice. When you share a page or link those sites may set cookies on your device or browser and may also make information about you publicly available or stored elsewhere. For more information about privacy and the cookies used by these services, as well as information on how to opt-out, please visit the respective social media platforms.</p>
    <h3>How can I manage my cookies?</h3>
    <p>
      You can use your website browser to:
    </p>
    <ul>
      <li>
        Delete all cookies
      </li>
      <li>
        Block all cookies
      </li>
      <li>
        Allow all cookies
      </li>
      <li>
        Block third-party cookies
      </li>
      <li>
        Clear all cookies when you close the browser
      </li>
      <li>
        Open a 'private browsing' / 'incognito' session (allows you to browse the internet without storing local data)
      </li>
      <li>
        Install add-ons and plug-ins to extend browser functionality, for example Google have created a <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">Google Analytics Opt-Out Browser Add-On</a> for Chrome.
      </li>
    </ul>
    <h3>More information about cookies</h3>
    <p>More information can be found on the Information Commissioner’s Office website, <a href="https://ico.org.uk" target="_blank">https://ico.org.uk</a>, <a href="http://aboutcookies.org/" target="_blank">http://aboutcookies.org/</a> and <a href="http://www.allaboutcookies.org/" target="_blank">http://www.allaboutcookies.org/</a></p>
  </div>
</Banner>

<style>
  h2 {
    margin: 1em 0;
  }
  .b-content__wrapper :global(p),
  .b-content__wrapper :global(li),
  .b-content__wrapper :global(a),
  .b-content__wrapper :global(span) {
    font-size: 16px;
    line-height: 24px;
  }
</style>
